# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'firebaseReactNavigationExample' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for test_google_signin
  pod 'GoogleSignIn', '~> 4.4.0'
  pod 'Firebase/Core', '~> 5.15.0'
  pod 'RNGoogleSignin', :path => '../node_modules/react-native-google-signin'

end