# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'firebaseReactNavigationExample' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  platform :ios, '9.0'
  pod 'Firebase/Core', '~> 5.15.0'
  # Pods for firebaseReactNavigationExample

  target 'firebaseReactNavigationExample-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'firebaseReactNavigationExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'firebaseReactNavigationExample-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for firebaseReactNavigationExample-tvOS



end
